### ISSUE TITLE
STM8S001RS485

### ISSUE THREAD

**Issue by niuyingxian** [TG9541/stm8s001rs485#1]
Can the modbus rtu source code of this project be shared? Where did I find it? Thank you

**Comment by TG9541** [comment]
I'm at it - the STM8 eForth core needs to be updated to 2.2.27.pre1 - and I'm at it.

**Comment by TG9541** [comment]
The code has been published and I also updated the KiCad project (slightly cleaner layout, RX/TX LED no longer inverted)
